site_name: Toran's Notes
repo_url: https://github.com/toransahu/notes/
site_author: Toran Sahu <toran.sahu@yahoo.com>
# nav:
#     - Home: index.md
#     - About: about.md
#     - Lang:
#         - Python:
#             - Basics: lang/python/Python-Basics.md
#             - Advanced: lang/python/Python-Advanced.md
#             - OOPs: lang/python/Python-OOPs.md
#             - Production: lang/python/Python-Production-Servers.md
#             - Testing: lang/python/Python-Testing.md
#         - Go: lang/golang/go.md
#     - CS Fundamentals:
#         - Algo: cs-fundamentals/Algo.md
#         - DBMS: cs-fundamentals/DBMS.md
#         - DS: cs-fundamentals/DS.md
#         - Network: cs-fundamentals/Network.md
#         - OS: cs-fundamentals/OS.md
#         - SE: cs-fundamentals/SE.md
#         - TOC: cs-fundamentals/ToC.md
#     - Android: android.md
#     - Blockchain: Blockchain.md
theme: 
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "-"
    - pymdownx.arithmatex:
    - pymdownx.superfences:
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
